export const IMG_CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const restaurantList = [
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "651453",
        name: "The Creamy Taste",
        uuid: "0891b3bb-57fc-4193-b468-9140e12cd33d",
        city: "6",
        area: "Baner",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "",
        cuisines: ["Indian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 47,
        minDeliveryTime: 47,
        maxDeliveryTime: 47,
        slaString: "47 MINS",
        lastMileTravel: 9.899999618530273,
        slugs: {
          restaurant: "the-creamy-taste-baner-baner",
          city: "pune",
        },
        cityState: "6",
        address:
          "SR NO. 1/1A/24, UJWAL PREMISES, SHOP NO. 2, BANER, Aundh, Pune, Maharashtra - 411045",
        locality: "Baner Road",
        parentId: 392103,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "9.8 kms",
        hasSurge: false,
        sla: {
          restaurantId: "651453",
          deliveryTime: 47,
          minDeliveryTime: 47,
          maxDeliveryTime: 47,
          lastMileTravel: 9.899999618530273,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.9",
        totalRatings: 20,
        new: false,
      },
      subtype: "basic",
      scrubber: {
        value: "RATING 4.9",
      },
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "618961",
        name: "Momo Zone - The Momo Company",
        uuid: "2fde41fc-423d-4773-9267-a12d61fd3059",
        city: "6",
        area: "Bhosari",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "vlbrqloyfmnztqxmqg0i",
        cuisines: ["Chinese", "Tibetan"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        slaString: "43 MINS",
        lastMileTravel: 7.400000095367432,
        slugs: {
          restaurant: "momo-zone---the-momo-company-bhosari-bhosari",
          city: "pune",
        },
        cityState: "6",
        address:
          "PRIVIA BUSINESS CENTER B WING 1ST FLOOR B 22 PLOT NO - 1 SEC - 6 MOSHI PRADHIKARAN (NEAR PCMC RTO) MOSHI 412105, PUNE PCMC ward No-3, Pune, Maharashtra, 412105",
        locality: "Moshi",
        parentId: 382343,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "40% off",
          shortDescriptionList: [
            {
              meta: "40% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "40% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.4 kms",
        hasSurge: false,
        sla: {
          restaurantId: "618961",
          deliveryTime: 43,
          minDeliveryTime: 43,
          maxDeliveryTime: 43,
          lastMileTravel: 7.400000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.9",
        totalRatings: 20,
        new: false,
      },
      subtype: "basic",
      scrubber: {
        value: "RATING 4.9",
      },
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "618962",
        name: "Indiana Burgers",
        uuid: "5abf4db4-d13a-4521-b25a-bc2262e4facd",
        city: "6",
        area: "Bhosari",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "jzqsz3j08s8ywhwntmhs",
        cuisines: ["Burgers", "American", "Fast Food", "Beverages", "Desserts"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        slaString: "42 MINS",
        lastMileTravel: 7.400000095367432,
        slugs: {
          restaurant: "indiana-burgers-bhosari-bhosari",
          city: "pune",
        },
        cityState: "6",
        address:
          "PRIVIA BUSINESS CENTER B WING 1ST FLOOR B 22 PLOT NO - 1 SEC - 6 MOSHI PRADHIKARAN (NEAR PCMC RTO) MOSHI 412105, PUNE PCMC ward No-3, Pune, Maharashtra, 412105",
        locality: "Moshi",
        parentId: 5714,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "40% off",
          shortDescriptionList: [
            {
              meta: "40% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "40% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.4 kms",
        hasSurge: false,
        sla: {
          restaurantId: "618962",
          deliveryTime: 42,
          minDeliveryTime: 42,
          maxDeliveryTime: 42,
          lastMileTravel: 7.400000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.9",
        totalRatings: 20,
        new: false,
      },
      subtype: "basic",
      scrubber: {
        value: "RATING 4.9",
      },
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "657285",
        name: "Juices & Shakes By Fse\t",
        uuid: "a708fed8-bc0a-4c73-8b8a-bb5b15cd3b53",
        city: "6",
        area: "Baner",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "e40e9fc6162274b3e8ab2f4a36459332",
        cuisines: ["Beverages", "Juices"],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        slaString: "39 MINS",
        lastMileTravel: 9.800000190734863,
        slugs: {
          restaurant: "juices-&-shakes-by-fse-baner-baner",
          city: "pune",
        },
        cityState: "6",
        address:
          "Shop No. 9, S.No, Sunflower Commercial, 77 Near, Prime Rose Mall Ln, near Dutta Mandir, Baner, Pune, Maharashtra 411045, India",
        locality: "Primrose The Mall",
        parentId: 394958,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "49% off",
          shortDescriptionList: [
            {
              meta: "49% off on all orders",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "49% off on all orders",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "49% OFF",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "49% off on all orders",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "NEW",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "9.8 kms",
        hasSurge: false,
        sla: {
          restaurantId: "657285",
          deliveryTime: 39,
          minDeliveryTime: 39,
          maxDeliveryTime: 39,
          lastMileTravel: 9.800000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.8",
        totalRatings: 20,
        new: true,
      },
      subtype: "basic",
      scrubber: {
        value: "RATING 4.8",
      },
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "619055",
        name: "Cupcake Bliss Cake & Desserts",
        uuid: "cd80d0f3-fbb4-4d6a-b6ef-74acc9d412da",
        city: "6",
        area: "Bhosari",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "40f193d8b23afb2988489dac1258962f",
        cuisines: ["Desserts", "Bakery"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 41,
        minDeliveryTime: 41,
        maxDeliveryTime: 41,
        slaString: "41 MINS",
        lastMileTravel: 7.400000095367432,
        slugs: {
          restaurant: "cupcake-bliss-cake-&-desserts-bhosari-bhosari-2",
          city: "pune",
        },
        cityState: "6",
        address:
          "PRIVIA BUSINESS CENTER B WING 1ST FLOOR B 22 PLOT NO - 1 SEC - 6 MOSHI PRADHIKARAN (NEAR PCMC RTO) MOSHI 412105, PUNE PCMC ward No-3, Pune, Maharashtra, 412105",
        locality: "Moshi Pradhikaran",
        parentId: 66732,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "40% off",
          shortDescriptionList: [
            {
              meta: "40% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "40% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.4 kms",
        hasSurge: false,
        sla: {
          restaurantId: "619055",
          deliveryTime: 41,
          minDeliveryTime: 41,
          maxDeliveryTime: 41,
          lastMileTravel: 7.400000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.8",
        totalRatings: 20,
        new: false,
      },
      subtype: "basic",
      scrubber: {
        value: "RATING 4.8",
      },
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "618965",
        name: "Kouzina Kafe - The Food Court",
        uuid: "f89c11dc-7cd6-4992-ba40-1c631dcd7f7b",
        city: "6",
        area: "Bhosari",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "wuxxl9b7ppx6goxn9mua",
        cuisines: ["Desserts", "Burgers", "Fast Food", "Beverages"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 41,
        minDeliveryTime: 41,
        maxDeliveryTime: 41,
        slaString: "41 MINS",
        lastMileTravel: 7.400000095367432,
        slugs: {
          restaurant: "kouzina-kafe---the-food-court-bhosari-bhosari",
          city: "pune",
        },
        cityState: "6",
        address:
          "PRIVIA BUSINESS CENTER B WING 1ST FLOOR B 22 PLOT NO - 1 SEC - 6 MOSHI PRADHIKARAN (NEAR PCMC RTO) MOSHI 412105, PUNE PCMC ward No-3, Pune, Maharashtra, 412105",
        locality: "Moshi",
        parentId: 249027,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "40% off",
          shortDescriptionList: [
            {
              meta: "40% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "40% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.4 kms",
        hasSurge: false,
        sla: {
          restaurantId: "618965",
          deliveryTime: 41,
          minDeliveryTime: 41,
          maxDeliveryTime: 41,
          lastMileTravel: 7.400000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.8",
        totalRatings: 20,
        new: false,
      },
      subtype: "basic",
      scrubber: {
        value: "RATING 4.8",
      },
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "618958",
        name: "The Dessert Zone",
        uuid: "60d10c61-3e74-47cb-9dda-093c94ee412d",
        city: "6",
        area: "Bhosari",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "c447c9ce7d0bbe78e46141e866236762",
        cuisines: ["Desserts", "Bakery"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 41,
        minDeliveryTime: 41,
        maxDeliveryTime: 41,
        slaString: "41 MINS",
        lastMileTravel: 7.400000095367432,
        slugs: {
          restaurant: "the-dessert-zone-bhosari-bhosari",
          city: "pune",
        },
        cityState: "6",
        address:
          "PRIVIA BUSINESS CENTER B WING 1ST FLOOR B 22 PLOT NO - 1 SEC - 6 MOSHI PRADHIKARAN (NEAR PCMC RTO) MOSHI 412105, PUNE PCMC ward No-3, Pune, Maharashtra, 412105",
        locality: "Moshi",
        parentId: 10414,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "40% off",
          shortDescriptionList: [
            {
              meta: "40% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "40% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.4 kms",
        hasSurge: false,
        sla: {
          restaurantId: "618958",
          deliveryTime: 41,
          minDeliveryTime: 41,
          maxDeliveryTime: 41,
          lastMileTravel: 7.400000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.8",
        totalRatings: 20,
        new: false,
      },
      subtype: "basic",
      scrubber: {
        value: "RATING 4.8",
      },
    },
    parentWidget: false,
  },
];
